//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiTraining.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowLeft {
            get {
                return ((int)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowTop {
            get {
                return ((int)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int comboBoxLanguagesAvailableIndex {
            get {
                return ((int)(this["comboBoxLanguagesAvailableIndex"]));
            }
            set {
                this["comboBoxLanguagesAvailableIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("french,english,latin,german,spanish")]
        public string ListOfLanguages {
            get {
                return ((string)(this["ListOfLanguages"]));
            }
            set {
                this["ListOfLanguages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"je,tu,il,elle,nous,vous,ils,elles,le,la,là,de,et,dans,est,pour,sur,ce,depuis,avoir,être,nouveau,plus,un,une,sera,maison,peut,si,page,mon,man,chercher,avait,libre,mais,ou,où,donc,or,ni,car,autre,autres,non,information,informations,temps,site,haut,que,quoi,quel,quels,quelle,quelles,leur,nouvelles,voir,seulement,quand,contact,ici,web,aussi,maintenant,aider,obtenir,été,comment,serait,service,services,des,sa,son,ses,trouver")]
        public string FrenchWords {
            get {
                return ((string)(this["FrenchWords"]));
            }
            set {
                this["FrenchWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"the,and,of,to,in,it,his,you,was,he,that,is,my,with,as,at,have,be,which,not,had,for,she,but,me,from,there,said,this,your,up,then,on,do,who,are,will,one,by,what,her,all,into,an,were,has,or,man,so,if,down,upon,been,when,very,could,we,out,am,may,him,own,would,some,must,how,street,see,know,before,should,most,little,now,just,no,house,minutes,other,eyes,our,indeed,two,matter,they,such,more,yet,door,looked,good,quite,majesty,three,case,think,half,only,face,nothing,once,five,found,lodge,front,heard,under,mind,seen,might,than,while,every,still,time,their,part,fire,over,remarked,too,where,gentleman,myself,well,note,without,paper,window,come,understand,about,them,shall,church,name,himself,doubt,us,soul,however,knew,friend,again,twice,room,work,seven,tell,much,came,long,left,right,address,o'clock,visitor,mask,small,make,asked,rather,its,made,hand,whom,back,none,say,person,king,men,take,throw,nature,baker,those,these,returned,dark,armchair,answered,six,side,give,clear,times,interested,enough,open,importance")]
        public string EnglishWords {
            get {
                return ((string)(this["EnglishWords"]));
            }
            set {
                this["EnglishWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tabControlMainIndexSelected {
            get {
                return ((int)(this["tabControlMainIndexSelected"]));
            }
            set {
                this["tabControlMainIndexSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eins,zwei,drei,vier,die,anderen,kinder,aber,alt,am,an,andere,arbeit,arbeite,auch,aus,badezimmer,bald,bäume,bei,bequemes,besuchen,bin,bisschen,blumen,dann,das,dazu,dem,den,der,des,die,dort,dreijährige,dunkel,ecke,eigentlich,ein,eine,einem,einen,einige,eltern,ersten,erzähle,es,essen,esstisch,familie,finde,freunde,für,garten,gehen,gehören,gehört,geht,gemütlich,gerne,gibt,grillen,groß,großeltern,großen,großer,haben,halbtags,hat,haus,hause,helfe,herd,heute,ich,im,immer,in,iran,isst,ist,jahre,kamin,keine,keller,kinder,kindergarten,kinderzimmer,klara,kleinen,kommen,kommt,können,küche,lampe,lang,lieber,liegt,macht,mag,manchmal,mann,mein,meine,meinen,meiner,mich,mit,mitte,möbel,mutter,nachmittag,nähe,natürlich,neben,nicht,noch,nur,oft,personen,quadratmeter,schlafzimmer,schön,schränke,schule,schwester,sechs,sehr,sie,sind,so,sofa,sohn,spaß,spielen,spülmaschine,stehen,steht,stühlen,teppich,tisch,tochter,und,uns,unser,unsere,unserem,unserer,viel,viele,vier,von,warm,waschmaschine,weiße,winter,wir,wohnen,wohnzimmer,zeit,zimmer,zimmers,zu,zwei")]
        public string GermanWords {
            get {
                return ((string)(this["GermanWords"]));
            }
            set {
                this["GermanWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"errare,humanum,est,pedonem,albinovanum,narrantem,audivimus,habitasse,se,supra,domum,papinii,is,erat,ex,turba,lucifugarum,inquit,circa,horam,tertiam,noctis,flagellorum,sonos,quaero,quid,faciat,dicitur,rationes,accipere,circa,horam,sextam,noctis,clamorem,concitatum,quaero,quid,sit,dicitur,vocem,exercere,quaero,circa,horam,octavam,noctis,quid,sibi,ille,sonus,rotarum,velit,gestari,dicitur,circa,lucem,discurritur,pueri,vocantur,cellari,coqui,tumultuantur,quaero,quid,sit,dicitur,mulsum,et,alicam,poposcisse,balneo,exisse,excedebat,inquis,ejus,cena,diem,minime,valde,enim,frugaliter,vivebat,nihil,consumebat,nisi,noctem")]
        public string LatinWords {
            get {
                return ((string)(this["LatinWords"]));
            }
            set {
                this["LatinWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"uno,dos,tres,acción,acciones,accionistas,actitud,además,administración,adquirir,al,alentada,alternativa,antes,antimonopolio,anunció,apoyo,asegurar,así,beneficiar,capital,carta,clientes,colegas,como,competencia,compromiso,comunicado,con,conjunto,consejo,consideramos,contar,de,del,después,determinación,duplicación,economía,el,empleados,en,equipos,espíritu,esta,estimados,favorablemente,finanzas,fondo,formalización,francés,francia,fue,fuente,futuro,ganador,ha,haber,han,hasta,hostil,igual,impulsados,incertidumbre,incondicional,independencia,inmediatamente,intención,intenciones,interesadas,la,lanzar,las,lo,marcha,más,mesa,meses,mi,ministro,mismo,momento,ni,no,nuestro,nuestros,numerosas,nunca,obligaciones,ocasiones,octubre,oferta,operativa,para,partes,participación,pasado,plazo,pleno,podéis,podrá,podría,poner,ponerse,por,posee,posible,positiva,presenta,primer,proponer,prórroga,protege,proyecto,pública,puedo,que,reactivación,recalcado,recibió,respetamos,riesgos,sé,septiembre,siendo,sigue,sobre,solicitado,solución,solucionado,su,sus,tenemos,tiempo,todas,total,trabajadores,un,una,valores,verdadera,vez,vuestro")]
        public string SpanishWords {
            get {
                return ((string)(this["SpanishWords"]));
            }
            set {
                this["SpanishWords"] = value;
            }
        }
    }
}
